---
- instrument: BTC
  group: B
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ Download of BTC Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    instrument: BTC
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    instrument: BTC
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    instrument: BTC
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    instrument: AMC
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: ETH
  group: E
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ Download of ETH Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    instrument: ETH
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    instrument: ETH
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    instrument: ETH
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    instrument: ETH
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: BNB
  group: B
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ Download of BNB Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    instrument: BNB
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    instrument: BNB
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    instrument: BNB
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    instrument: BNB
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: USDT
  group: U
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ Download of USDT Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    instrument: USDT
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    instrument: USDT
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    instrument: USDT
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    instrument: USDT
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: ADA
  group: A
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ Download of ADA Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    instrument: ADA
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    instrument: ADA
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    instrument: ADA
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    instrument: ADA
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: XRP
  group: X
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ Download of XRP Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    instrument: XRP
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    instrument: XRP
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    instrument: XRP
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    instrument: XRP
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: DOGE
  group: D
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ Download of DOGE Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    instrument: DOGE
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    instrument: DOGE
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    instrument: DOGE
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    instrument: DOGE
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
