---
- instrument: AMC
  group: Materials
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance - Download of AMC Historical Data File"
    group: "Yahoo Finance - Historical Data"
    instrument: AMC.AX
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: rsi
    desc: RSI Check - 14 Days
    group: "RSI [ 14 Day ]"
    instrument: AMC
    period: 14
    min: 10
    max: 90
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    instrument: AMC
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    instrument: AMC
    period: 5
  - name: strategy
    desc: "STRATEGY - Moving Averages"
    group: "STRATEGY: [ Moving Averages ]"
    instrument: AMC
    file: moving_averages.py
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    instrument: AMC
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: ANC
  group: Materials
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance - Download of AMC Historical Data File"
    group: "Yahoo Finance - Historical Data"
    instrument: ANC 
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: rsi
    desc: RSI Check - 14 Days
    group: "RSI [ 14 Day ]"
    instrument: ANC
    period: 14
    min: 10
    max: 90
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    instrument: ANC
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    instrument: ANC
    period: 5
  - name: strategy
    desc: "STRATEGY - Moving Averages"
    group: "STRATEGY: [ Moving Averages ]"
    instrument: ANC
    file: moving_averages.py
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    instrument: ANC
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: APT
  group: Materials
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance - Download of AMC Historical Data File"
    group: "Yahoo Finance - Historical Data"
    instrument: APT
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: rsi
    desc: RSI Check - 14 Days
    group: "RSI [ 14 Day ]"
    instrument: APT
    period: 14
    min: 10
    max: 90
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    instrument: APT
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    instrument: APT
    period: 5
  - name: strategy
    desc: "STRATEGY - Moving Averages"
    group: "STRATEGY: [ Moving Averages ]"
    instrument: APT
    file: moving_averages.py
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    instrument: APT
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: BHP
  group: Materials
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance - Download of AMC Historical Data File"
    group: "Yahoo Finance - Historical Data"
    instrument: BHP
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: rsi
    desc: RSI Check - 14 Days
    group: "RSI [ 14 Day ]"
    instrument: BHP
    period: 14
    min: 10
    max: 90
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    instrument: BHP
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    instrument: BHP
    period: 5
  - name: strategy
    desc: "STRATEGY - Moving Averages"
    group: "STRATEGY: [ Moving Averages ]"
    instrument: BHP
    file: moving_averages.py
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    instrument: BHP
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: TLS
  group: Materials
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance - Download of AMC Historical Data File"
    group: "Yahoo Finance - Historical Data"
    instrument: TLS
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: rsi
    desc: RSI Check - 14 Days
    group: "RSI [ 14 Day ]"
    instrument: TLS
    period: 14
    min: 10
    max: 90
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    instrument: TLS
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    instrument: TLS
    period: 5
  - name: strategy
    desc: "STRATEGY - Moving Averages"
    group: "STRATEGY: [ Moving Averages ]"
    instrument: TLS
    file: moving_averages.py
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    instrument: TLS
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
