---
- instrument: BTC
  group: B
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ BTC Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    ticker: BTC
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: BTC
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: BTC
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: AMC
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: ETH
  group: E
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ ETH Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    ticker: ETH
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: ETH
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: ETH
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: ETH
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: BNB
  group: B
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ BNB Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    ticker: BNB
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: BNB
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: BNB
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: BNB
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: USDT
  group: U
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ USDT Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    ticker: USDT
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: USDT
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: USDT
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: USDT
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: ADA
  group: A
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ ADA Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    ticker: ADA
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: ADA
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: ADA
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: ADA
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: XRP
  group: X
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ XRP Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    ticker: XRP
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: XRP
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: XRP
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: XRP
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: DOGE
  group: D
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ DOGE Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    ticker: DOGE
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: DOGE
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: DOGE
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: DOGE
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: USDC
  group: U
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ USDC Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    ticker: USDC
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: USDC
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    instrument: USDC
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: USDC
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: DOT
  group: D
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ DOT Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    ticker: DOT
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: DOT
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: DOT
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: DOT
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: SOL
  group: S
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ SOL Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    ticker: SOL
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: SOL
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: SOL
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: SOL
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: UNI
  group: U
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ UNI Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    ticker: UNI
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: UNI
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: UNI
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: UNI
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: BCH
  group: B
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ BCH Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    ticker: BCH
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: BCH
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    instrument: BCH
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: BCH
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: BUSD
  group: B
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ BUSD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    ticker: BUSD
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: BUSD
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: BUSD
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    instrument: BUSD
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: LINK
  group: L
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ LINK Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    ticker: LINK
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: LINK
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: LINK
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: LINK
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: LTC
  group: L
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ LTC Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    ticker: LTC
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: LTC
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: LTC
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: LTC
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: LUNA
  group: L
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ LTC Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    instrument: LUNA
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: LUNA
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: LUNA
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: LUNA
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: WBTC
  group: W
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ WBTC Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    ticker: WBTC
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: WBTC
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    instrument: WBTC
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: WBTC
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: MATIC
  group: M
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ MATIC Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    instrument: MATIC
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: MATIC
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: MATIC
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: MATIC
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: ETC
  group: E
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ ETC Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    ticker: ETC
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: ETC
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: ETC
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: ETC
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: XLM
  group: X
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ XLM Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    ticker: XLM
    start_date: 1597479263
    end_date: 1629015263
    interval: 1d
    adjusted_close: true
    frequency: daily
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: XLM
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: XLM
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: XLM
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
