---
- instrument: BTC-USD
  group: B
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ BTC-USD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1597479263
    period2: 1629015263
    interval: 1d
    adjusted_close: true
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: BTC-USD
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: BTC-USD
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: BTC-USD
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: ETH-USD
  group: E
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ ETH-USD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1597479263
    period2: 1629015263
    interval: 1d
    adjusted_close: true
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: ETH-USD
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: ETH-USD
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: ETH-USD
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: BNB-USD
  group: B
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ BNB-USD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1597479263
    period2: 1629015263
    interval: 1d
    adjusted_close: true
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: BNB-USD
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: BNB-USD
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: BNB-USD
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: USDT-USD
  group: U
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ USDT-USD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1597479263
    period2: 1629015263
    interval: 1d
    adjusted_close: true
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: USDT-USD
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: USDT-USD
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: USDT-USD
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: ADA-USD
  group: A
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ ADA-USD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1597479263
    period2: 1629015263
    interval: 1d
    adjusted_close: true
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: ADA-USD
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: ADA-USD
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: ADA-USD
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: XRP-USD
  group: X
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ XRP-USD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1597479263
    period2: 1629015263
    interval: 1d
    adjusted_close: true
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: XRP-USD
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: XRP-USD
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: XRP-USD
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: DOGE-USD
  group: D
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ DOGE-USD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1597479263
    period2: 1629015263
    interval: 1d
    adjusted_close: true
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: DOGE-USD
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: DOGE-USD
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: DOGE-USD
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: USDC-USD
  group: U
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ USDC-USD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1597479263
    period2: 1629015263
    interval: 1d
    adjusted_close: true
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: USDC-USD
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    instrument: USDC-USD
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: USDC-USD
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: DOT-USD
  group: D
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ DOT-USD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1597479263
    period2: 1629015263
    interval: 1d
    adjusted_close: true
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: DOT-USD
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: DOT-USD
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: DOT-USD
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: SOL-USD
  group: S
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ SOL-USD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1597479263
    period2: 1629015263
    interval: 1d
    adjusted_close: true
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: SOL-USD
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: SOL-USD
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: SOL-USD
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: UNI1-USD
  group: U
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ UNI1-USD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1597479263
    period2: 1629015263
    interval: 1d
    adjusted_close: true
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: UNI1-USD
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: UNI1-USD
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: UNI1-USD
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: BCH-USD
  group: B
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ BCH-USD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1597479263
    period2: 1629015263
    interval: 1d
    adjusted_close: true
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: BCH-USD
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    instrument: BCH-USD
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: BCH-USD
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: BUSD-USD
  group: B
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ BUSD-USD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1597479263
    period2: 1629015263
    interval: 1d
    adjusted_close: true
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: BUSD-USD
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: BUSD-USD
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    instrument: BUSD-USD
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: LINK-USD
  group: L
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ LINK-USD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1597479263
    period2: 1629015263
    interval: 1d
    adjusted_close: true
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: LINK-USD
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: LINK-USD
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: LINK-USD
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: LTC-USD
  group: L
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ LTC-USD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1597479263
    period2: 1629015263
    interval: 1d
    adjusted_close: true
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: LTC-USD
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: LTC-USD
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: LTC-USD
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: LUNA1-USD
  group: L
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ LUNA1-USD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1597479263
    period2: 1629015263
    interval: 1d
    adjusted_close: true
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: LUNA1-USD
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: LUNA1-USD
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: LUNA1-USD
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: WBTC-USD
  group: W
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ WBTC-USD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1597479263
    period2: 1629015263
    interval: 1d
    adjusted_close: true
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: WBTC-USD
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    instrument: WBTC
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: WBTC-USD
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: MATIC-USD
  group: M
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ MATIC-USD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1597479263
    period2: 1629015263
    interval: 1d
    adjusted_close: true
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: MATIC-USD
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: MATIC-USD
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: MATIC-USD
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: ETC-USD
  group: E
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ ETC-USD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1597479263
    period2: 1629015263
    interval: 1d
    adjusted_close: true
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: ETC-USD
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: ETC-USD
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: ETC-USD
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
- instrument: XLM-USD
  group: X
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ XLM-USD Historical Data File ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1597479263
    period2: 1629015263
    interval: 1d
    adjusted_close: true
  - name: sma
    desc: "Simple Moving Average - 50 Days"
    group: "SMA: [ 50 Day ]"
    ticker: XLM-USD
    period: 50
  - name: sma
    desc: "Simple Moving Average - 5 Days"
    group: "SMA: [ 5 Day ]"
    ticker: XLM-USD
    period: 5
  - name: backtest
    desc: "BACKTEST: [ Moving Averages ]"
    group: "Backtesting"
    ticker: XLM-USD
    file: backtest_moving_averages.py
    shares: 1000
    capital: 100000
