---
- instrument: EUR/USD
  group: Majors
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ EUR/USD ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1147737600
    period2: 1644624000
    interval: 1d
    includeAdjustedClose: true
  - name: backtest
    desc: "BACKTEST: [ RSI2 ]"
    group: "Backtesting"
    file: rsi2.py
    shares: 1000
    capital: 1000000
    data_format: yahoo_finance_data
    rsiPeriod: 50
    entrySMA: 200
    exitSMA: 5
    rsiPeriod: 2
    overSoldThreshold: 90
    overBoughtThreshold: 10
- instrument: USD/JPY
  group: Majors
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ USD/JPY ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1147737600
    period2: 1644624000
    interval: 1d
    includeAdjustedClose: true
  - name: backtest
    desc: "BACKTEST: [ RSI2 ]"
    group: "Backtesting"
    file: rsi2.py
    shares: 1000
    capital: 1000000
    data_format: yahoo_finance_data
    rsiPeriod: 50
    entrySMA: 200
    exitSMA: 5
    rsiPeriod: 2
    overSoldThreshold: 90
    overBoughtThreshold: 10
- instrument: EUR/USD
  group: Majors
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ EUR/USD ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1147737600
    period2: 1644624000
    interval: 1d
    includeAdjustedClose: true
  - name: backtest
    desc: "BACKTEST: [ RSI2 ]"
    group: "Backtesting"
    file: rsi2.py
    shares: 1000
    capital: 1000000
    data_format: yahoo_finance_data
    rsiPeriod: 50
    entrySMA: 200
    exitSMA: 5
    rsiPeriod: 2
    overSoldThreshold: 90
    overBoughtThreshold: 10
- instrument: GBP/USD
  group: Majors
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ GBP/USD ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1147737600
    period2: 1644624000
    interval: 1d
    includeAdjustedClose: true
  - name: backtest
    desc: "BACKTEST: [ RSI2 ]"
    group: "Backtesting"
    file: rsi2.py
    shares: 1000
    capital: 1000000
    data_format: yahoo_finance_data
    rsiPeriod: 50
    entrySMA: 200
    exitSMA: 5
    rsiPeriod: 2
    overSoldThreshold: 90
    overBoughtThreshold: 10    
- instrument: AUD/USD
  group: Commodity Currencies
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ AUD/USD ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1147737600
    period2: 1644624000
    interval: 1d
    includeAdjustedClose: true
  - name: backtest
    desc: "BACKTEST: [ RSI2 ]"
    group: "Backtesting"
    file: rsi2.py
    shares: 1000
    capital: 1000000
    data_format: yahoo_finance_data
    rsiPeriod: 50
    entrySMA: 200
    exitSMA: 5
    rsiPeriod: 2
    overSoldThreshold: 10
    overBoughtThreshold: 90    
- instrument: USD/CAD
  group: Commodity Currencies
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ USD/CAD ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1147737600
    period2: 1644624000
    interval: 1d
    includeAdjustedClose: true
  - name: backtest
    desc: "BACKTEST: [ RSI2 ]"
    group: "Backtesting"
    file: rsi2.py
    shares: 1000
    capital: 1000000
    data_format: yahoo_finance_data
    rsiPeriod: 50
    entrySMA: 200
    exitSMA: 5
    rsiPeriod: 2
    overSoldThreshold: 10
    overBoughtThreshold: 90    
- instrument: NZD/USD
  group: Commodity Currencies
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ NZD/USD ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1147737600
    period2: 1644624000
    interval: 1d
    includeAdjustedClose: true
  - name: backtest
    desc: "BACKTEST: [ RSI2 ]"
    group: "Backtesting"
    file: rsi2.py
    shares: 1000
    capital: 1000000
    data_format: yahoo_finance_data
    rsiPeriod: 50
    entrySMA: 200
    exitSMA: 5
    rsiPeriod: 2
    overSoldThreshold: 10
    overBoughtThreshold: 90    

- instrument: GBP/EUR
  group: Commodity Currencies
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ GBP/EUR ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1147737600
    period2: 1644624000
    interval: 1d
    includeAdjustedClose: true
  - name: backtest
    desc: "BACKTEST: [ RSI2 ]"
    group: "Backtesting"
    file: rsi2.py
    shares: 1000
    capital: 1000000
    data_format: yahoo_finance_data
    rsiPeriod: 50
    entrySMA: 200
    exitSMA: 5
    rsiPeriod: 2
    overSoldThreshold: 10
    overBoughtThreshold: 90    
- instrument: EUR/CHF
  group: Commodity Currencies
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ EUR/CHF ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1147737600
    period2: 1644624000
    interval: 1d
    includeAdjustedClose: true
  - name: backtest
    desc: "BACKTEST: [ RSI2 ]"
    group: "Backtesting"
    file: rsi2.py
    shares: 1000
    capital: 1000000
    data_format: yahoo_finance_data
    rsiPeriod: 50
    entrySMA: 200
    exitSMA: 5
    rsiPeriod: 2
    overSoldThreshold: 10
    overBoughtThreshold: 90    
- instrument: EUR/JPY
  group: Commodity Currencies
  plugin:
  - name: yahoo_finance_data
    desc: "Yahoo Finance [ EUR/JPY ]"
    group: "Yahoo Finance [ Historical Data ]"
    period1: 1147737600
    period2: 1644624000
    interval: 1d
    includeAdjustedClose: true
  - name: backtest
    desc: "BACKTEST: [ RSI2 ]"
    group: "Backtesting"
    file: rsi2.py
    shares: 1000
    capital: 1000000
    data_format: yahoo_finance_data
    rsiPeriod: 50
    entrySMA: 200
    exitSMA: 5
    rsiPeriod: 2
    overSoldThreshold: 10
    overBoughtThreshold: 90
